//tealium universal tag - utag.158 ut4.0.201608120710, Copyright 2016 Tealium.com Inc. All Rights Reserved.
window.criteo_q=window.criteo_q||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"test_page_format":"page_format"};u.extend=[function(a,b){if(typeof b['ut.profile']!="undefined"&&b['ut.profile']!="wotif"&&b['ut.profile']!="partnerships"){return false;}
window.crto_wotifHotelsAU="21634";window.crto_wotifHotelsNZ="24758";window.crto_wotifPackagesAU="24759";window.crto_wotifPackagesNZ="24760";window.crto_criteoPartnerId;if(typeof b['ut.profile']!="undefined"&&b['ut.profile']=="wotif"){window.parseHomepage=function(){var pathName=document.location.pathname;var hostName=document.location.hostname;if(pathName=="/Hotels"&&hostName=="www.wotif.com"){window.crto_criteoPartnerId=window.crto_wotifHotelsAU}
if(pathName=="/Holidays"&&hostName=="www.wotif.com"){window.crto_criteoPartnerId=window.crto_wotifPackagesAU}
if(pathName=="/Hotels"&&hostName=="www.wotif.co.nz"){window.crto_criteoPartnerId=window.crto_wotifHotelsNZ}
if(pathName=="/Holidays"&&hostName=="www.wotif.co.nz"){window.crto_criteoPartnerId=window.crto_wotifPackagesNZ}
return window.crto_criteoPartnerId};window.setPartnerId=function(){var lobName=b.domain;var hostName=document.location.hostname;if(lobName=="HOTEL"&&hostName=="www.wotif.com"){window.crto_criteoPartnerId=window.crto_wotifHotelsAU}
if(lobName=="PACKAGE"&&hostName=="www.wotif.com"){window.crto_criteoPartnerId=window.crto_wotifPackagesAU}
if(lobName=="HOTEL"&&hostName=="www.wotif.co.nz"){window.crto_criteoPartnerId=window.crto_wotifHotelsNZ}
if(lobName=="PACKAGE"&&hostName=="www.wotif.co.nz"){window.crto_criteoPartnerId=window.crto_wotifPackagesNZ}
return window.crto_criteoPartnerId};}else if(typeof b['ut.profile']!="undefined"&&b['ut.profile']=="partnerships"){window.parseHomepage=function(){window.crto_criteoPartnerId="00000";return window.crto_criteoPartnerId};window.setPartnerId=function(){window.crto_criteoPartnerId="00000";return window.crto_criteoPartnerId};}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"//static.criteo.net/js/ld/ld.js"
};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
var crto_pageType=b.pageType;var crto_deviceType=b.device_type;var crto_criteoTagType;var crto_criteoSiteType;switch(crto_pageType){case"Infosite":crto_criteoTagType="viewItem"
break;case"Home":case"Landing":crto_criteoTagType="viewHome"
break;case"Search":crto_criteoTagType="viewList"
break;case"Confirmation":crto_criteoTagType="trackTransaction"
break;default:break;}
switch(crto_deviceType){case"Desktop":crto_criteoSiteType="d"
break;case"Mobile":crto_criteoSiteType="m"
break;default:crto_criteoSiteType="d";break;}
function widgetCall(){var crto_criteoPartnerId=window.parseHomepage();crto_criteoPartnerId=window.setPartnerId();var crto_hashedEmail="";window.criteo_q=window.criteo_q||[];if(crto_criteoTagType=="viewHome"){window.criteo_q.push({event:"setAccount",account:crto_criteoPartnerId},{event:"setHashedEmail",email:crto_hashedEmail},{event:"setSiteType",type:crto_criteoSiteType},{event:"viewHome"});}
if(crto_criteoTagType=="viewItem"){var productId;if(b.hotelId&&(crto_criteoPartnerId==crto_wotifHotelsAU||crto_criteoPartnerId==crto_wotifHotelsNZ||crto_criteoPartnerId==crto_partnershipsHotels)){productId=b.hotelId;}
var departureAirport;var arrivalAirport;if(crto_criteoPartnerId==crto_wotifPackagesAU||crto_criteoPartnerId==crto_wotifPackagesNZ||crto_criteoPartnerId==crto_partnershipsPackages){arrivalAirport=b.entity.packageSearch.packageSearchParameters.flightSearchParameters.arrivalAirport;departureAirport=b.entity.packageSearch.packageSearchParameters.flightSearchParameters.departureAirport;var thisArrivalId=Math.floor(Math.random()*3)+1;productId=departureAirport+"/"+arrivalAirport+thisArrivalId;}
window.criteo_q.push({event:"setAccount",account:crto_criteoPartnerId},{event:"setHashedEmail",email:crto_hashedEmail},{event:"setSiteType",type:crto_criteoSiteType},{event:"viewItem",item:productId});}
if(crto_criteoTagType=="viewList"){var productIdArray=[];var checkInDate;var checkOutDate;if(b.checkInDate){checkInDate=b.checkInDate;}
if(b.checkOutDate){checkOutDate=b.checkOutDate;}
var hotelIdList;if(b.firstThreeHotels&&(crto_criteoPartnerId==crto_wotifHotelsAU||crto_criteoPartnerId==crto_wotifHotelsNZ||crto_criteoPartnerId==crto_partnershipsHotels)){hotelIdList=b.firstThreeHotels.split("|");productIdArray=hotelIdList;}
var packageIdList;var departureAirport;var arrivalAirport;if(crto_criteoPartnerId==crto_wotifPackagesAU||crto_criteoPartnerId==crto_wotifPackagesNZ||crto_criteoPartnerId==crto_partnershipsPackages){departureAirport=b.entity.packageFHSearch.packageFHSearchParameters.packageFlightSearchParameters.departureAirportTLA;arrivalAirport=b.entity.packageFHSearch.packageFHSearchParameters.packageFlightSearchParameters.arrivalAirportTLA;productIdArray.push(departureAirport+"/"+arrivalAirport+"1");productIdArray.push(departureAirport+"/"+arrivalAirport+"2");productIdArray.push(departureAirport+"/"+arrivalAirport+"3");}
window.criteo_q.push({event:"setAccount",account:crto_criteoPartnerId},{event:"setHashedEmail",email:crto_hashedEmail},{event:"setSiteType",type:crto_criteoSiteType},{event:"viewList",item:productIdArray},{event:"viewSearch",checkin_date:checkInDate,checkout_date:checkOutDate});}
if(crto_criteoTagType=="trackTransaction"){var productId;var transactionPrice;var transactionId=b.entity.checkout.trl
if(crto_criteoPartnerId==crto_wotifHotelsAU||crto_criteoPartnerId==crto_wotifHotelsNZ||crto_criteoPartnerId==crto_partnershipsHotels){productId=b.hotelId;transactionPrice=b.entity.checkout.cartTotal.amount;}
var departureAirport;var arrivalAirport;if(crto_criteoPartnerId==crto_wotifPackagesAU||crto_criteoPartnerId==crto_wotifPackagesNZ||crto_criteoPartnerId==crto_partnershipsPackages){arrivalAirport=b.entity.packageSearch.packageSearchParameters.flightSearchParameters.arrivalAirport||b.entity.checkout.flightOffer.destinationAirportCode||"";departureAirport=b.entity.packageSearch.packageSearchParameters.flightSearchParameters.departureAirport||b.entity.checkout.flightOffer.originAirportCode||"";productId=departureAirport+"/"+arrivalAirport+"1";transactionPrice=1;}
window.criteo_q.push({event:"setAccount",account:crto_criteoPartnerId},{event:"setHashedEmail",email:crto_hashedEmail},{event:"setSiteType",type:crto_criteoSiteType},{event:"trackTransaction",id:transactionId,item:[{id:productId,price:transactionPrice,quantity:1}]});}}
widgetCall();u.loader_cb=function(){u.initialized=true;};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_158'});}
}};utag.o[loader].loader.LOAD(id);})("158","expedia.orbitz");}catch(error){utag.DB(error);}
